inp = input('Enter your username :')
print("Bot : Hello, how are u", inp)
rep = input("YOU :")
print("Bot : that's nice, im good too! Nice to meet u. What are you doing this day ?")
per = input("YOU : ")
print("Bot : I see i see, personally im just here doing some bots activitys")
erp = input("YOU :")
print("Sûre, no problem ! Hope to see you again")